AWSTemplateFormatVersion: "2010-09-09"
Description: my workflow
Resources:
  my-workflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: my workflow
      Name: my-workflow
  Jobingestion:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: "3"
        ScriptLocation: ingestion/ingestion.py
      DefaultArguments:
        --arguments: '{"raw_path":"s3://rawStorageBucket/raw/","schema":{"description":"string","id":"int"},"source_path":"s3://sourceBucket/source/"}'        
      Role: "iam-role-arn"

  Jobtransformation:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: "3"
        ScriptLocation: transformations/transform.py
      DefaultArguments:
        --arguments: '{"years":[2021,2022]}'

      Role: "iam-role-arn"

  transformationTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Description: trigger transformation
      Predicate:
        Conditions:
        - JobName: ingestion
          LogicalOperator: EQUALS
          State: SUCCEEDED
  ingestionTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Description: "trigger ingestion"
