AWSTemplateFormatVersion: "2010-09-09"
Description: my workflow
Resources:
  Workflow_my-workflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: my workflow
      Name: my-workflow
  Job_ingestion:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: "3"
        ScriptLocation: ingestion/ingestion.py
      DefaultArguments:
        --arguments: '{"raw_path":"s3://rawStorageBucket/raw/","schema":{"description":"string","id":"int"},"source_path":"s3://sourceBucket/source/"}'        
      Role: "iam-role-arn"
  Job_transformation:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: "3"
        ScriptLocation: transformations/transform.py
      DefaultArguments:
        --arguments: '{"years":[2021,2022]}'
      Role: "iam-role-arn"
  Trigger_transformation:
    Type: AWS::Glue::Trigger
    Properties:
      Description: trigger transformation
      Predicate:
        Conditions:
        - JobName: ingestion
          LogicalOperator: EQUALS
          State: SUCCEEDED

  Trigger_ingestion:
    Type: AWS::Glue::Trigger
    Properties:
      Description: "trigger ingestion"
