AWSTemplateFormatVersion: "2010-09-09"
Description: my workflow
Resources:
  WorkflowMyWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: my workflow
      Name: my-workflow
      Tags:
        lob: "sales"

  TriggerStartWorkflowMyWorkflow:
    Type: AWS::Glue::Trigger
    Properties:
      Name: trigger-start-my-workflow
      Type: SCHEDULED
      Schedule: cron(00 20 * * ? *)
      StartOnCreation: true
      WorkflowName: 
        Ref: WorkflowMyWorkflow
      Actions:
        - JobName:
            Ref: JobIngestion

  JobIngestion:
    Type: AWS::Glue::Job
    Properties:
      Name: ingestion
      Command:
        Name: pythonshell
        PythonVersion: "3"
        ScriptLocation: ingestion/ingestion.py
      DefaultArguments:
        --arguments: '{"raw_path":"s3://rawStorageBucket/raw/","schema":{"description":"string","id":"int"},"source_path":"s3://sourceBucket/source/"}'        
        --additional-python-modules: "openpyxl==3.0.9,Office365-REST-Python-Client"
      Role: "iam-role-arn"
      Tags:
        team: "fantastic-team"
        region: "us-west-1"

  JobTransformation:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: "3"
        ScriptLocation: transformations/transform.py
      DefaultArguments:
        --arguments: '{"years":[2021,2022]}'
        --additional-python-modules: "openpyxl==3.0.9,Office365-REST-Python-Client"
      Role: iam-role-arn
      Name: transformation

  TriggerTransformation:
    Type: AWS::Glue::Trigger
    Properties:
      Description: trigger transformation
      Type: CONDITIONAL
      Predicate:
        Conditions:
        - JobName: ingestion
          LogicalOperator: EQUALS
          State: SUCCEEDED
      Actions:
        - JobName: 
            Ref: JobTransformation

  # TriggerIngestion:
  #   Type: AWS::Glue::Trigger
  #   Properties:
  #     Description: "trigger ingestion"
  #     Actions:
  #       - JobName: 
  #           Ref: Job_ingestion
