version: "0.1"

name: my-workflow
schedule:
  cron: "00 20 * * ? *"
tags:
  team: "fantastic-team"

workflow:
  - extract_to_raw_storage
  - load_to_ods
  - build_dim
  - build_fact:
      allow_failure: true
  - build_dm

jobs:
  ingestion:
    description: "extract log from excel to s3"
    type: python
    entrypoint: raw/ingestion.py
    args:
      source_path: s3://sourceBucket/source/
      raw_path: s3://rawStorageBucket/raw/
    tags:
      team: "fantastic-team"
      region: "us-west-1"

  transform:
    description: "load log to ods"
    type: glue-sql
    entrypoint: ods/ods.sql
