version: "0.1"

workflow:
  - extract_to_raw_storage
  - load_to_ods
  - build_dim
  - build_fact
  - build_dm

jobs:
  extract_to_raw_storage:
    description: "extract log from excel to s3"
    type: python
    entrypoint: raw/ingestion.py
    args:
      source_path: s3://sourceBucket/source/
      raw_path: s3://rawStorageBucket/raw/
  
  load_to_ods:
    description: "load log to ods"
    type: glue-sql
    entrypoint: ods/ods.sql

  build_dim:
    description: "build dim"
    type: glue-sql
    entrypoint: dw/dim.sql

  build_fact:
    description: "build fact"
    type: glue-sql
    entrypoint: dw/fact.sql

  build_dm:
    description: "build fact"
    type: redshift
    entrypoint: dm/dm.sql
