name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45
    - run: go mod download
    - run: go install github.com/markbates/pkger/cmd/pkger
    - run: make build
    - run: make e2e
    - run: make release
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: dp
        retention-days: 3
