name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - run: go install github.com/markbates/pkger/cmd/pkger
    - run: pkger
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45
    - run: go mod download
    - run: go build
